---
#- name: debian | adding ruby ppa
#  apt_repository:
#    repo: "ppa:brightbox/ruby-ng"
#    state: present
#    validate_certs: no

- name: debian | installing pre-reqs
  apt:
    name: "{{ item }}"
    state: present
  with_items:
#    - bundler
    - imagemagick
    - libmysqlclient-dev
    - libyaml-dev
    - libxml2-dev
    - libxslt-dev
    - git
    - ruby1.9.3
    - ruby1.9.3-dev
