---
- name: debian | adding ruby ppa
  apt_repository:
    repo: "ppa:brightbox/ruby-ng"
    state: present
    
- name: debian | installing pre-reqs
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - bundler
    - imagemagick
    - libyaml-dev
    - libxml2-dev
    - libxslt-dev
    - git
    - ruby2.2
